### ISSUE TITLE
print brackets missing in segment.py on line 26

### ISSUE THREAD

**Issue by marilin99** [mubastan/segment-py#1]

**Comment by mubastan** [comment]
Thanks, fixed. It was written in Python 2, which did not require parenthesis in print statements. Not sure if the code works on Python 3.

**Comment by marilin99** [comment]
It works pretty well in py3, some stuff is deprecated at least with my libraries, e.g the scipy.misc.imread() is removed from scipy version 1.2.0, so I substituted with cv2.imread() instead (probably would work with any image reader, as long as the output format matches)
